-- ecsite schema (PostgreSQL 17)
-- Source: doc/詳細設計/ecsite-ER図・テーブル定義書.md
-- Executed by the postgres image's docker-entrypoint-initdb.d on first startup only
-- (i.e. when the postgres-data volume is empty). Runs before 02_create_readonly_user.sh,
-- so readonly_user gets SELECT on these tables.
-- Tables are created in dependency order. IF NOT EXISTS makes the script safe to re-run manually.

-- Trigram index support for partial-match product search (ILIKE '%keyword%')
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- users
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY,
    email          varchar(255) NOT NULL,
    password_hash  varchar(255) NOT NULL,
    name           varchar(100) NOT NULL,
    phone_number   varchar(20),
    created_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lower CHECK (email = lower(email))
);

COMMENT ON TABLE  users               IS 'ユーザー';
COMMENT ON COLUMN users.email         IS 'メールアドレス（ログインID、小文字に正規化）';
COMMENT ON COLUMN users.password_hash IS 'パスワードのハッシュ値（BCrypt）';
COMMENT ON COLUMN users.name          IS '氏名';
COMMENT ON COLUMN users.phone_number  IS '電話番号（ハイフンなし）';

-- ============================================================
-- addresses
-- ============================================================
CREATE TABLE IF NOT EXISTS addresses (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    user_id         bigint       NOT NULL,
    recipient_name  varchar(100) NOT NULL,
    postal_code     char(7)      NOT NULL,
    prefecture      varchar(10)  NOT NULL,
    city            varchar(100) NOT NULL,
    address_line    varchar(200) NOT NULL,
    building        varchar(200),
    phone_number    varchar(20)  NOT NULL,
    is_default      boolean      NOT NULL DEFAULT false,
    created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_addresses_postal_code CHECK (postal_code ~ '^[0-9]{7}$')
);

-- One default address per user
CREATE UNIQUE INDEX IF NOT EXISTS uq_addresses_user_default
    ON addresses (user_id) WHERE is_default = true;
CREATE INDEX IF NOT EXISTS ix_addresses_user_id
    ON addresses (user_id);

COMMENT ON TABLE  addresses                IS '配送先住所';
COMMENT ON COLUMN addresses.user_id        IS '所有ユーザー';
COMMENT ON COLUMN addresses.recipient_name IS '宛名';
COMMENT ON COLUMN addresses.postal_code    IS '郵便番号（ハイフンなし7桁）';
COMMENT ON COLUMN addresses.prefecture     IS '都道府県';
COMMENT ON COLUMN addresses.city           IS '市区町村';
COMMENT ON COLUMN addresses.address_line   IS '町名・番地';
COMMENT ON COLUMN addresses.building       IS '建物名・部屋番号';
COMMENT ON COLUMN addresses.phone_number   IS '配送用の電話番号（ハイフンなし）';
COMMENT ON COLUMN addresses.is_default     IS '既定の配送先（1ユーザーにつき最大1件）';

-- ============================================================
-- categories
-- ============================================================
CREATE TABLE IF NOT EXISTS categories (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY,
    name           varchar(50) NOT NULL,
    display_order  integer     NOT NULL DEFAULT 0,
    created_at     timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     timestamp   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT uq_categories_name UNIQUE (name)
);

COMMENT ON TABLE  categories               IS 'カテゴリ';
COMMENT ON COLUMN categories.name          IS 'カテゴリ名';
COMMENT ON COLUMN categories.display_order IS '表示順（昇順）';

-- ============================================================
-- products
-- ============================================================
CREATE TABLE IF NOT EXISTS products (
    id              bigint       GENERATED BY DEFAULT AS IDENTITY,
    category_id     bigint       NOT NULL,
    name            varchar(200) NOT NULL,
    description     text,
    price           integer      NOT NULL,
    stock_quantity  integer      NOT NULL DEFAULT 0,
    image_url       varchar(500),
    is_published    boolean      NOT NULL DEFAULT true,
    version         integer      NOT NULL DEFAULT 0,
    created_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT ck_products_price CHECK (price >= 0),
    CONSTRAINT ck_products_stock_quantity CHECK (stock_quantity >= 0)
);

CREATE INDEX IF NOT EXISTS ix_products_category_id
    ON products (category_id);
CREATE INDEX IF NOT EXISTS ix_products_name_trgm
    ON products USING gin (name gin_trgm_ops);

COMMENT ON TABLE  products                IS '商品';
COMMENT ON COLUMN products.category_id    IS 'カテゴリ';
COMMENT ON COLUMN products.name           IS '商品名';
COMMENT ON COLUMN products.description    IS '商品説明';
COMMENT ON COLUMN products.price          IS '販売価格（税込・円）';
COMMENT ON COLUMN products.stock_quantity IS '在庫数';
COMMENT ON COLUMN products.image_url      IS '商品画像のURL';
COMMENT ON COLUMN products.is_published   IS '公開フラグ（false は一覧・検索・詳細に表示しない）';
COMMENT ON COLUMN products.version        IS '楽観ロック用バージョン（JPA @Version）';

-- ============================================================
-- cart_items
-- ============================================================
CREATE TABLE IF NOT EXISTS cart_items (
    id          bigint    GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint    NOT NULL,
    product_id  bigint    NOT NULL,
    quantity    integer   NOT NULL DEFAULT 1,
    created_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cart_items PRIMARY KEY (id),
    CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cart_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT uq_cart_items_user_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_cart_items_quantity CHECK (quantity >= 1)
);

COMMENT ON TABLE  cart_items            IS 'カート明細';
COMMENT ON COLUMN cart_items.user_id    IS 'カートの持ち主';
COMMENT ON COLUMN cart_items.product_id IS '商品';
COMMENT ON COLUMN cart_items.quantity   IS '数量';

-- ============================================================
-- orders
-- ============================================================
CREATE TABLE IF NOT EXISTS orders (
    id                       bigint       GENERATED BY DEFAULT AS IDENTITY,
    order_number             varchar(20)  NOT NULL,
    user_id                  bigint       NOT NULL,
    status                   varchar(20)  NOT NULL DEFAULT 'ORDERED',
    payment_method           varchar(20)  NOT NULL,
    subtotal_amount          integer      NOT NULL,
    shipping_fee             integer      NOT NULL,
    total_amount             integer      NOT NULL,
    shipping_recipient_name  varchar(100) NOT NULL,
    shipping_postal_code     char(7)      NOT NULL,
    shipping_prefecture      varchar(10)  NOT NULL,
    shipping_city            varchar(100) NOT NULL,
    shipping_address_line    varchar(200) NOT NULL,
    shipping_building        varchar(200),
    shipping_phone_number    varchar(20)  NOT NULL,
    ordered_at               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_order_number UNIQUE (order_number),
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_orders_status CHECK (status IN ('ORDERED', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT ck_orders_payment_method CHECK (payment_method IN ('CREDIT_CARD', 'BANK_TRANSFER', 'CASH_ON_DELIVERY')),
    CONSTRAINT ck_orders_subtotal_amount CHECK (subtotal_amount >= 0),
    CONSTRAINT ck_orders_shipping_fee CHECK (shipping_fee >= 0),
    CONSTRAINT ck_orders_total_amount CHECK (total_amount = subtotal_amount + shipping_fee),
    CONSTRAINT ck_orders_shipping_postal_code CHECK (shipping_postal_code ~ '^[0-9]{7}$')
);

CREATE INDEX IF NOT EXISTS ix_orders_user_ordered_at
    ON orders (user_id, ordered_at DESC);

COMMENT ON TABLE  orders                         IS '注文';
COMMENT ON COLUMN orders.order_number            IS '注文番号（画面・メール表示用）';
COMMENT ON COLUMN orders.user_id                 IS '注文したユーザー';
COMMENT ON COLUMN orders.status                  IS '注文ステータス（ORDERED/SHIPPED/DELIVERED/CANCELLED）';
COMMENT ON COLUMN orders.payment_method          IS '支払方法（CREDIT_CARD/BANK_TRANSFER/CASH_ON_DELIVERY）';
COMMENT ON COLUMN orders.subtotal_amount         IS '商品合計（税込・円）';
COMMENT ON COLUMN orders.shipping_fee            IS '送料（税込・円）';
COMMENT ON COLUMN orders.total_amount            IS '支払総額（税込・円）';
COMMENT ON COLUMN orders.shipping_recipient_name IS '配送先の宛名（購入時点の値）';
COMMENT ON COLUMN orders.shipping_postal_code    IS '配送先の郵便番号（購入時点の値）';
COMMENT ON COLUMN orders.shipping_prefecture     IS '配送先の都道府県（購入時点の値）';
COMMENT ON COLUMN orders.shipping_city           IS '配送先の市区町村（購入時点の値）';
COMMENT ON COLUMN orders.shipping_address_line   IS '配送先の町名・番地（購入時点の値）';
COMMENT ON COLUMN orders.shipping_building       IS '配送先の建物名（購入時点の値）';
COMMENT ON COLUMN orders.shipping_phone_number   IS '配送先の電話番号（購入時点の値）';
COMMENT ON COLUMN orders.ordered_at              IS '注文日時';

-- ============================================================
-- order_items (no updated_at: rows are never updated after creation)
-- ============================================================
CREATE TABLE IF NOT EXISTS order_items (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    order_id      bigint       NOT NULL,
    product_id    bigint       NOT NULL,
    product_name  varchar(200) NOT NULL,
    unit_price    integer      NOT NULL,
    quantity      integer      NOT NULL,
    subtotal      integer      NOT NULL,
    created_at    timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_quantity CHECK (quantity >= 1),
    CONSTRAINT ck_order_items_subtotal CHECK (subtotal = unit_price * quantity)
);

CREATE INDEX IF NOT EXISTS ix_order_items_product_id
    ON order_items (product_id);

COMMENT ON TABLE  order_items              IS '注文明細';
COMMENT ON COLUMN order_items.order_id     IS '注文';
COMMENT ON COLUMN order_items.product_id   IS '商品';
COMMENT ON COLUMN order_items.product_name IS '商品名（購入時点の値）';
COMMENT ON COLUMN order_items.unit_price   IS '単価（購入時点の products.price）';
COMMENT ON COLUMN order_items.quantity     IS '数量';
COMMENT ON COLUMN order_items.subtotal     IS '小計（unit_price * quantity）';
